<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>frame</string>
		<string>textframe</string>
	</array>
	<key>firstLineMatch</key>
	<string>^/* textframe v</string>
	<key>foldingStartMarker</key>
	<string></string>
	<key>foldingStopMarker</key>
	<string></string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>textframe</string>
	<key>patterns</key>
	<array/>
	<key>scopeName</key>
	<string>text.frame</string>
	<key>uuid</key>
	<string>2DDFD531-718E-4B83-B3A1-041D76A1DD76</string>
</dict>
</plist>
